### ISSUE TITLE
Warning occurs

### ISSUE THREAD

**Issue by kazuyk** [brstefanovic/easyinject#1]
After install and activate this plugin, I got the following warning message when I saved a navigation menu in Appearance - Menu in Admin screen:

> Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'EI_Main' does not have a method 'save' in .../wp-includes/plugin.php on line 525

**Environment**
- PHP 5.6.18
- WordPress 4.5
- Theme: BizVektor 1.8.19

**Comment by brstefanovic** [comment]
Fixed in the latest revision.

**Comment by kazuyk** [comment]
Confirmed.

**Comment by kazuyk** [comment]
Confirmed.
